/*
 * pdc_tf_poly_sched.h
 *
 * Polynomial-based GPU selection scheduler for PDC Data Flyway.
 *
 * Uses a degree-3 polynomial fitted offline on 2,400 data points of ZFP GPU
 * compression under varying GEMM contention levels to predict total
 * transformation time (H2D + compression + D2H) for each available GPU.
 * The GPU with the lowest predicted total_ms is selected.
 *
 * Model features (6 total):
 *   x0 = data_size_mb    -- size of data to transform
 *   x1 = gpu_util        -- GPU utilization % (0-100)
 *   x2 = power_mw        -- GPU power draw in milliwatts
 *   x3 = mem_used_mb     -- GPU memory used in MB
 *   x4 = prev_d2h_ms     -- previous D2H transfer time in ms
 *   x5 = prev_total_ms   -- previous total transformation time in ms
 *
 * R² = 0.9853  MAE = 2.209 ms  (Rank 15 from exhaustive feature search)
 *
 * Polynomial evaluation:
 *   The degree-3 polynomial over 6 features produces terms of the form
 *   x_i^a * x_j^b * x_k^c where a+b+c <= 3. The coefficients are loaded
 *   from a file generated by export_coefficients.py at initialization time.
 *
 * Usage:
 *   1. Call pdc_tf_poly_sched_init() at server startup.
 *   2. Call pdc_tf_poly_select_gpu() before each transformation to get the
 *      best GPU index.
 *   3. Call pdc_tf_poly_update() after each transformation to record lag.
 *   4. Call pdc_tf_poly_sched_finalize() at server shutdown.
 */

#ifndef PDC_TF_POLY_SCHED_H
#define PDC_TF_POLY_SCHED_H

#include <stdint.h>
#include "pdc_tf_profiler.h"

/* ── polynomial model constants ──────────────────────────────────────────── */
#define PDC_POLY_N_FEATURES   4       /* number of input features             */
#define PDC_POLY_DEGREE       3       /* polynomial degree                    */

/* Maximum number of polynomial terms for degree=3, n_features=6:
 * C(6+3, 3) = C(9,3) = 84 terms                                            */
#define PDC_POLY_MAX_TERMS    84

/* ── polynomial model state ──────────────────────────────────────────────── */
typedef struct {
    double coefficients[PDC_POLY_MAX_TERMS]; /* fitted coefficients           */
    int    n_terms;                           /* actual number of terms        */
    int    powers[PDC_POLY_MAX_TERMS][PDC_POLY_N_FEATURES]; /* exponent matrix */
    int    initialized;                       /* 1 if loaded successfully      */
} pdc_tf_poly_model_t;

extern pdc_tf_poly_model_t pdc_tf_poly_model;

/* ── init / finalize ─────────────────────────────────────────────────────
 * Load polynomial coefficients from coeff_file (generated by
 * export_coefficients.py). Must be called before pdc_tf_poly_select_gpu().
 *
 * Returns 0 on success, -1 on failure.
 * ─────────────────────────────────────────────────────────────────────── */
int pdc_tf_poly_sched_init(const char *coeff_file);
void pdc_tf_poly_sched_finalize(void);

/* ── predict total transformation time for one GPU ───────────────────────
 * Given a feature vector, evaluate the degree-3 polynomial and return
 * the predicted total_ms. Returns -1.0 on error.
 *
 * features[0] = data_size_mb
 * features[1] = gpu_util       (0-100)
 * features[2] = power_mw
 * features[3] = mem_used_mb
 * features[4] = prev_d2h_ms   (-1.0 if no prior observation)
 * features[5] = prev_total_ms (-1.0 if no prior observation)
 * ─────────────────────────────────────────────────────────────────────── */
double pdc_tf_poly_predict(const double features[PDC_POLY_N_FEATURES]);

/* ── select best GPU ─────────────────────────────────────────────────────
 * Queries NVML for each GPU, builds the feature vector, evaluates the
 * polynomial, and returns the index of the GPU with lowest predicted
 * total_ms.
 *
 * data_size_mb : size of the region to be transformed in MB
 *
 * Returns GPU device index (0 to nvml_device_count-1).
 * Falls back to lowest-utilization GPU if model is not initialized.
 * ─────────────────────────────────────────────────────────────────────── */
int pdc_tf_poly_select_gpu(double data_size_mb);

/* ── update lag features after transformation ────────────────────────────
 * Record observed timings for device_index so they become lag features
 * for the next scheduling decision on that device.
 *
 * Wraps pdc_tf_update_device_lag() from pdc_tf_profiler.h.
 * ─────────────────────────────────────────────────────────────────────── */
void pdc_tf_poly_update(unsigned int device_index,
                         double       h2d_ms,
                         double       comp_ms,
                         double       d2h_ms,
                         double       total_ms);

#endif /* PDC_TF_POLY_SCHED_H */